name: Environment and Sustainability
slug: environment_and_sustainability
order: 5
projects:
- path: projects/model-anganwadi-project.md
- path: projects/biomass-project-punjab.md
- path: projects/slts-project-saharsat.md
